/********************************************************************************
 *  NetFPGA-10G http://www.netfpga.org
 *
 *  File:
 *        boq_cpu_regs_defines.v
 *
 *  Module:
 *        boq_cpu_regs_defines
 *
 *  Author:
 *        Noa Zilberman
 *
 *  Description:
 *        This file is automatically generated with the registers defintions towards the CPU/Software
 *
 *  Copyright notice:
 *        Copyright (C) 2013 University of Cambridge
 *
 *  Licence:
 *        This file is part of the NetFPGA 10G development base package.
 *
 *        This file is free code: you can redistribute it and/or modify it under
 *        the terms of the GNU Lesser General Public License version 2.1 as
 *        published by the Free Software Foundation.
 *
 *        This package is distributed in the hope that it will be useful, but
 *        WITHOUT ANY WARRANTY; without even the implied warranty of
 *        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *        Lesser General Public License for more details.
 *
 *        You should have received a copy of the GNU Lesser General Public
 *        License along with the NetFPGA source package.  If not, see
 *        http://www.gnu.org/licenses/.
 *
 */

           `define  REG_ID_BITS        31:0
           `define  REG_ID_WIDTH        32
           `define  REG_ID_DEFAULT        32'h0000DA03
           `define  REG_ID_ADDR        32'h0
           `define  REG_VERSION_BITS        31:0
           `define  REG_VERSION_WIDTH        32
           `define  REG_VERSION_DEFAULT        32'h1
           `define  REG_VERSION_ADDR        32'h4
           `define  REG_FLIP_BITS        31:0
           `define  REG_FLIP_WIDTH        32
           `define  REG_FLIP_DEFAULT        32'h0
           `define  REG_FLIP_ADDR        32'h8
           `define  REG_COUNTERIN_BITS        31:0
           `define  REG_COUNTERIN_WIDTH        32
           `define  REG_COUNTERIN_DEFAULT        32'h0
           `define  REG_COUNTERIN_ADDR        32'hC
           `define  REG_COUNTEROUT_BITS        31:0
           `define  REG_COUNTEROUT_WIDTH        32
           `define  REG_COUNTEROUT_DEFAULT        32'h0
           `define  REG_COUNTEROUT_ADDR        32'h10
           `define  REG_DEBUG_BITS        31:0
           `define  REG_DEBUG_WIDTH        32
           `define  REG_DEBUG_DEFAULT        32'h0
           `define  REG_DEBUG_ADDR        32'h14
